### ISSUE TITLE
Push 0.1.2 to npm.

### ISSUE THREAD

**Issue by electic** [mynewsdesk/react-text-carousel#2]
It seems when trying to install this, it doesn't find 0.1.2.

**Comment by pedrophalves** [comment]
Hello? I am having the same problem, can't use loopPhrases props because of this.

**Comment by el1f** [comment]
Hey @AndreasArledal, can you push the 0.1.2 or are you still waiting to add some more improvements?

**Comment by AndreasArledal** [comment]
Sorry for the delay. I've started a rewrite. Hopefully I'll be able to publish it over the weekend.

**Comment by oyeanuj** [comment]
@AndreasArledal Any updates? Using from master directly, this is what I get:
```
ERROR in ./node_modules/react-text-carousel/lib/components/TextCarousel.js
Module parse failed: Unexpected token (9:19)
You may need an appropriate loader to handle this file type.
|
| class TextCarousel extends Component {
|   static propTypes = {
|     phrases: PropTypes.arrayOf(PropTypes.string).isRequired,
|     interval: PropTypes.number,
 @ ./node_modules/react-text-carousel/lib/index.js 1:0-53

```

**Comment by el1f** [comment]
Dude, is there any chance we'll be seeing this one ever published?

**Comment by el1f** [comment]
Bump

**Comment by el1f** [comment]
Well, guess it'd officially dead now

**Comment by electic** [comment]
Sounds like it is dead (author abandoned). Going to close this issue out so it disappears from my dashboard.
