### ISSUE TITLE
Demo link not working

### ISSUE THREAD

**Issue by oyeanuj** [mynewsdesk/react-text-carousel#3]
Hi @AndreasArledal! Thank you for sharing this library. It seems that the demo link isn't working, could you please take a look? I'd love to test this library out!

**Comment by AndreasArledal** [comment]
Hi @oyeanuj, fixed, but the demo doesn't give much more information at the moment. However it should be really easy to try it out by just following the [usage example in the readme](https://github.com/AndreasArledal/react-text-carousel#usage).
